### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by atennapel** [groupoid/henk#40]
Hi, this is a very nice project. Since pure is based on the Calculus of Constructions, there are two worries one could have:
- Although you can state the induction principle for an inductive type, you can not prove it. So even though you have dependent types, without induction these are not particularly useful (I think).
- There is no way to write an efficient pattern matching function for an inductive type in CoC. For example when defining a natural number datatype, you cannot write a predecessor function that runs in O(1). 

Have you thought about these things, or are the irrelevant?

**Comment by 5HT** [comment]
Yes, this is pure CoC, no derivable induction principle, but with universes. If you want to play with your concerns please refer to Cedile and Formality. This project is dedicated to provide clean extraction path of any dep type language to Erlang VM.

**Comment by atennapel** [comment]
Aah I see, thanks.
